### ISSUE TITLE
apt-key deprecated, ansible fails installing docker 

### ISSUE THREAD

**Issue by bobdolectf** [chadgeary/cloudblock#106]
Ansible build fails to install docker

![image](https://github.com/chadgeary/cloudblock/assets/46633387/ec3aa87b-0537-4c69-b18c-872d06e15c22)

Current code with issue
```
- name: Docker apt key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0640'

       - name: Docker apt repo
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
```
Code fix, remove the lines above and add the following (update all playbooks making sure to update the architecture as required)
```
- name: Add repo using key from URL
      deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: '{{ ansible_distribution_release }}'
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/ubuntu/gpg
```

Ansible documentation: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/deb822_repository_module.html
