### ISSUE TITLE
Couldn't resolve module/action 'deb822_repository'

### ISSUE THREAD

**Issue by Calvin-GG** [chadgeary/cloudblock#112]
Followed instructions on a fresh ubuntu install and get this error when I run the final command: 

```
ERROR! couldn't resolve module/action 'deb822_repository'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/cloudblock/playbooks/cloudblock_amd64.yml': line 23, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Add repo using key from URL
      ^ here
      
```

that file looks like this: 

```
--
- name: Cloudblock - amd64 standalone variant
  hosts: localhost
  gather_facts: true
  become: true
  tasks:

    - name: Custom facts
      ansible.builtin.set_fact:
        url_from_doh_provider:
          adguard: https://dns.adguard.com/dns-query
          cloudflare: https://cloudflare-dns.com/dns-query
          cloudflare-security: https://security.cloudflare-dns.com/dns-query
          cloudflare-family: https://family.cloudflare-dns.com/dns-query
          applied-privacy: https://doh.applied-privacy.net/query
          google: https://dns.google/dns-query
          hurricane-electric: https://ordns.he.net/dns-query
          pi-dns: https://doh.pi-dns.com/dns-query
          quad9-recommended: https://dns.quad9.net/dns-query
          libre-dns: https://doh.libredns.gr/dns-query
          opendns: https://doh.opendns.com/dns-query

    - name: Add repo using key from URL
      deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: '{{ ansible_distribution_release }}'
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/ubuntu/gpg

    - name: Dpkg Architecture
      ansible.builtin.shell: |
        dpkg --print-architecture
      register: dpkg_arch

```
