### ISSUE TITLE
Downloading external resources degrades performance

### ISSUE THREAD

**Issue by pemsith** [chadgeary/cloudblock#113]
**Description**
Tasks that directly download resources from external sources during runtime (e.g., get_url) causes high memory usage. This issue is particularly noticeable in environments with large-scale deployments or limited system resources. The below instance we are reporting as part of this bug that we would like to get resolved.

\playbooks\cloudblock_gcp.yml
```
    - name: Get wireguard backup from storage if exists
      get_url:
        url: https://storage.googleapis.com/{{ gcp_project_prefix }}-bucket-{{ gcp_project_suffix }}/wireguard/wireguard_backup.tar.gz
        timeout: 120
        owner: root
        group: root
        mode: '0640'
        dest: /opt/wireguard_backup.tar.gz
        headers:
          Authorization: Bearer {{ gcs_token_resp.json.access_token }}
      ignore_errors: true
```

**Expected behavior**
The playbook should avoid fetching resources directly from external URLs to prevent high memory usage. Instead:
- Pre-fetch the required resources to a control machine or staging area ahead of deployment.
- Use local copies or mirrors for fetching files.
- This approach would reduce memory usage and improve the performance and reliability of deployments.

**Versions (please complete the following information):**
 - OS - centos 9
 - Ansible core 2.15.8
