### ISSUE TITLE
Create a dictionary file for DOH_PROVIDER

### ISSUE THREAD

**Issue by chadgeary** [chadgeary/cloudblock#32]
e.g.
```
{
  "adguard": "https://dns.adguard.com/dns-query",
  "cloudflare": "https://cloudflare-dns.com/dns-query"
}
```

**Comment by chadgeary** [comment]
Parsing json via ansible looks like:
```
      - name: read json file content
        shell: cat doh_providers.json
        register: doh_providers_content

      - name: parse json from content
        set_fact:
          doh_providers: "{{ doh_providers_content.stdout | from_json }}"

      - name: set a doh_url
        set_fact:
          doh_url: "{{ doh_providers | json_query(jmesquery) }}"
        vars:
          jmesquery: "{{ adguard }}"
```
